#!/usr/bin/env python3# code from: gemma LLM Agent
# User initial request: None
'''This code have been generated by an LLM Agent'''

import requests


def get_joke():
    response = requests.get("https://official-joke-api.appspot.com/random_joke")
    data = response.json()
    setup = data['setup']
    punchline = data['punchline']
    return f"Setup: {setup}\n\nPunchline: {punchline}"


if __name__ == "__main__":
    print(get_joke())
