#!/usr/bin/env python3# code from: gemma LLM Agent
# User initial request: None
'''This code have been generated by an LLM Agent'''

import requests

def get_dog_image():
    # Make a GET request to the dog images API
    response = requests.get("https://dog.ceo/api/breeds/image/random")

    # Check if the request was successful
    if response.status_code == 200:
        # Convert the response to JSON format
        data = response.json()

        # Return the image URL
        return data["message"]

if __name__ == "__main__":
    # Print a random dog image
    print(get_dog_image())
