#!/usr/bin/env python3# code from: gemma_3_7b LLM Agent
# User initial request: None
'''This code have been generated by an LLM Agent'''

import requests

def get_age(name):
    url = 'https://api.agify.io?name={}'.format(name)
    response = requests.get(url)
    return response.json()['age']

age = get_age('Junko')
print('The age of Junko is: {}'.format(age))
